//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 07:07:11 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://example.com/playlist/orderPlaylist", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.playlist.orderPlaylist;
