//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.24 at 06:29:25 AM CEST 
//


package com.example.playlist.shufflePlaylist;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.playlist.shufflePlaylist package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.playlist.shufflePlaylist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShufflePlaylistRequest }
     * 
     */
    public ShufflePlaylistRequest createShufflePlaylistRequest() {
        return new ShufflePlaylistRequest();
    }

    /**
     * Create an instance of {@link ShufflePlaylistResponse }
     * 
     */
    public ShufflePlaylistResponse createShufflePlaylistResponse() {
        return new ShufflePlaylistResponse();
    }

}
