//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 12:13:24 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://example.com/playlist/registering", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.playlist.registering;
